// <auto-generated />
using System;
using DocuCheck.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocuCheck.Infrastructure.Migrations
{
    [DbContext(typeof(DocuCheckDbContext))]
    partial class DocuCheckDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DocuCheck.Domain.Entities.ChecksHistory.CheckHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CheckHistory");
                });

            modelBuilder.Entity("DocuCheck.Domain.Entities.ChecksHistory.CheckHistory", b =>
                {
                    b.OwnsOne("DocuCheck.Domain.Entities.ChecksHistory.Enums.CheckResult", "CheckResult", b1 =>
                        {
                            b1.Property<Guid>("CheckHistoryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Message")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RecordedAtRaw")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ResultType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CheckHistoryId");

                            b1.ToTable("CheckHistory");

                            b1.WithOwner()
                                .HasForeignKey("CheckHistoryId");
                        });

                    b.Navigation("CheckResult")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
